In [11]:
import pandas as pd

In [12]:
data=pd.read_csv("scores_data.csv")
data

         Batch  User_ID     Score
0    AI_ELITE_7  uid_149       6 / 7
1    AI_ELITE_7  uid_148       6 / 7
2    AI_ELITE_7  uid_147       7 / 7
3    AI_ELITE_7  uid_146       7 / 7
4    AI_ELITE_7  uid_145       4 / 7
..          ...      ...         ...
144  AI_ELITE_4    uid_5       4 / 7
145  AI_ELITE_4    uid_4       4 / 7
146  AI_ELITE_4    uid_3       4 / 7
147  AI_ELITE_4    uid_2       3 / 7
148  AI_ELITE_4    uid_1       2 / 7

[149 rows x 3 columns]

In [13]:
data.isnull().sum()

Batch          0
User_ID        0
   Score       0
dtype: int64

In [14]:
data.duplicated().sum()

np.int64(0)

In [17]:
data.columns

Index(['Batch ', 'User_ID ', '   Score   '], dtype='object')

In [20]:
data.columns = data.columns.str.strip()
data.Batch.value_counts()

Batch
AI_ELITE_7    53
AI_ELITE_6    48
AI_ELITE_4    48
Name: count, dtype: int64

In [22]:
# Extract numeric score
data['Score_Num'] = data['Score'].str.split('/').str[0].astype(int)

In [23]:
data

          Batch  User_ID  Score  Score_Num
0    AI_ELITE_7  uid_149  6 / 7          6
1    AI_ELITE_7  uid_148  6 / 7          6
2    AI_ELITE_7  uid_147  7 / 7          7
3    AI_ELITE_7  uid_146  7 / 7          7
4    AI_ELITE_7  uid_145  4 / 7          4
..          ...      ...    ...        ...
144  AI_ELITE_4    uid_5  4 / 7          4
145  AI_ELITE_4    uid_4  4 / 7          4
146  AI_ELITE_4    uid_3  4 / 7          4
147  AI_ELITE_4    uid_2  3 / 7          3
148  AI_ELITE_4    uid_1  2 / 7          2

[149 rows x 4 columns]

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Batch      149 non-null    object
 1   User_ID    149 non-null    object
 2   Score      149 non-null    object
 3   Score_Num  149 non-null    int64
dtypes: int64(1), object(3)
memory usage: 4.8+ KB

In [25]:
data.describe()

        Score_Num
count  149.000000
mean     4.382550
std      1.592199
min      0.000000
25%      3.000000
50%      4.000000
75%      5.000000
max      7.000000

In [26]:
data['Score_Num'].value_counts().sort_index()

Score_Num
0     2
1     3
2    12
3    24
4    40
5    32
6    18
7    18
Name: count, dtype: int64

In [27]:
data.groupby('Batch')['Score_Num'].agg(
    avg_score='mean',
    max_score='max',
    min_score='min',
    students='count'
).sort_values(by='avg_score', ascending=False)

            avg_score  max_score  min_score  students
Batch
AI_ELITE_7   5.056604          7          2        53
AI_ELITE_6   4.229167          7          0        48
AI_ELITE_4   3.791667          7          0        48

In [28]:
def performance(score):
    if score >= 6:
        return 'Excellent'
    elif score >= 4:
        return 'Average'
    else:
        return 'Needs Improvement'

data['Performance'] = data['Score_Num'].apply(performance)
data['Performance'].value_counts()

Performance
Average              72
Needs Improvement    41
Excellent            36
Name: count, dtype: int64

In [29]:
data

          Batch  User_ID  Score  Score_Num        Performance
0    AI_ELITE_7  uid_149  6 / 7          6          Excellent
1    AI_ELITE_7  uid_148  6 / 7          6          Excellent
2    AI_ELITE_7  uid_147  7 / 7          7          Excellent
3    AI_ELITE_7  uid_146  7 / 7          7          Excellent
4    AI_ELITE_7  uid_145  4 / 7          4            Average
..          ...      ...    ...        ...                ...
144  AI_ELITE_4    uid_5  4 / 7          4            Average
145  AI_ELITE_4    uid_4  4 / 7          4            Average
146  AI_ELITE_4    uid_3  4 / 7          4            Average
147  AI_ELITE_4    uid_2  3 / 7          3  Needs Improvement
148  AI_ELITE_4    uid_1  2 / 7          2  Needs Improvement

[149 rows x 5 columns]

In [30]:
data.groupby(['Batch', 'Performance']).size().unstack(fill_value=0)

Performance  Average  Excellent  Needs Improvement
Batch
AI_ELITE_4        27          4                 17
AI_ELITE_6        24          9                 15
AI_ELITE_7        21         23                  9

Conclusion

AI_ELITE_7 (Top Performing Batch)

Highest number of Excellent performers (23) indicates strong mastery of ML concepts.
Lowest Needs Improvement count (9) shows consistent and effective learning outcomes.
Batch is ready for advanced ML topics and real-world project implementation.

AI_ELITE_6 (Moderate / Balanced Batch)

Majority of students fall under the Average category (24), indicating partial understanding.
Balanced distribution of performance levels reflects mixed learning outcomes.
With focused practice and revision, many students can be upgraded to Excellent level.

AI_ELITE_4 (Low Performing Batch)
Very low Excellent count (4) highlights weak conceptual clarity in ML fundamentals.
High Needs Improvement (17) count indicates learning gaps.
Batch requires foundational reinforcement and guided hands-on training.